import { ChevronLeft, ChevronRight, ShoppingCart } from "lucide-react";
import AnalyticsPanel from "./AnalyticsPanel";
import { formatCurrency, formatDate, formatNumber } from "../utils";

const TransactionsPanel = ({ transactions, currency, page, onPageChange }) => (
  <AnalyticsPanel title="Recent transactions" icon={ShoppingCart} action={<span className="text-[10px] font-bold text-slate-400">{formatNumber(transactions?.total)} total</span>}>
    <div className="-mx-4 mt-2 overflow-x-auto sm:-mx-5"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-100 text-[10px] font-black uppercase tracking-wider text-slate-400"><th className="px-4 py-3 sm:px-5">Date</th><th className="px-4 py-3 sm:px-5">Order ID</th><th className="px-4 py-3 sm:px-5">Quantity</th><th className="px-4 py-3 sm:px-5">Buying price</th><th className="px-4 py-3 sm:px-5">Selling price</th><th className="px-4 py-3 sm:px-5">Revenue</th><th className="px-4 py-3 sm:px-5">Profit</th></tr></thead><tbody>{(transactions?.items || []).map((transaction) => <tr key={transaction.id} className="border-b border-slate-100 last:border-0"><td className="px-4 py-3 text-xs font-semibold text-slate-600 sm:px-5">{formatDate(transaction.date)}</td><td className="px-4 py-3 text-xs font-black text-slate-900 sm:px-5">#{String(transaction.orderId).slice(-8)}</td><td className="px-4 py-3 text-xs font-bold text-slate-700 sm:px-5">{formatNumber(transaction.quantity)}</td><td className="px-4 py-3 text-xs font-semibold text-slate-500 sm:px-5">{formatCurrency(transaction.buyingPrice, currency)}</td><td className="px-4 py-3 text-xs font-semibold text-slate-700 sm:px-5">{formatCurrency(transaction.sellingPrice, currency)}</td><td className="px-4 py-3 text-xs font-black text-slate-900 sm:px-5">{formatCurrency(transaction.revenue, currency)}</td><td className="px-4 py-3 text-xs font-bold text-emerald-600 sm:px-5">{formatCurrency(transaction.profit, currency)}</td></tr>)}</tbody></table>{!transactions?.items?.length && <p className="px-5 py-8 text-center text-sm font-semibold text-slate-500">No transactions in this period.</p>}</div>
    {transactions?.totalPages > 1 && <div className="flex items-center justify-end gap-2 border-t border-slate-100 pt-3"><button disabled={page === 1} onClick={() => onPageChange(page - 1)} aria-label="Previous page" className="rounded-lg border border-slate-200 p-1.5 text-slate-600 disabled:cursor-not-allowed disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span className="text-xs font-bold text-slate-500">Page {page} of {transactions.totalPages}</span><button disabled={page === transactions.totalPages} onClick={() => onPageChange(page + 1)} aria-label="Next page" className="rounded-lg border border-slate-200 p-1.5 text-slate-600 disabled:cursor-not-allowed disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div>}
  </AnalyticsPanel>
);

export default TransactionsPanel;
